# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

# do this before all your .NET Core tasks
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- script: dotnet test $(System.DefaultWorkingDirectory)/**/TestCodeCoverageProject.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'test with coverage'

- task: PublishCodeCoverageResults@1
  displayName: 'publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

