# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature-stage
# testing the trigger for our feature branch

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: PowerShell@2
  inputs:
    script: 'Write-Host "Hello Sebi"! We are just playing with the Pipeline now.'