# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  #vmImage: 'ubuntu-latest'
  name: 'SelfHostedPcAlberto'

variables:
  buildConfiguration: 'Release'
  imageName: 'pipelines-dotnet-core-dockerhub'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

#https://docs.microsoft.com/es-es/azure/devops/pipelines/tasks/build/docker?view=azure-devops
steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    command: build
    Dockerfile: Dockerfile