# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - script: echo "building..."
    displayName: "Echo Building"
  - script: echo "will fail"
    displayName: "If Succed Parameter"
    condition: eq(${{ parameters.succeed}}, false)
  - script: |
      if ["${{parameters.succeed}}" == "False"]
      then
        exit 1
      fi
      exit 0
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
