---

### Create a new file for the Azure Pipelines

trigger:
- feature-stage

variables:
  buildConfiguration: 'Release'
  subscription: 'loginsp'

stages:
# BUILD THE WEB APP - RESTORE, BUILD, TEST, PUBLISH, PUBLISH BUILD ARTIFACTS
- stage: build_app
  displayName: 'Build the Web App'
  jobs:
  - job: build_app_job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore Dependencies'
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Buld the Web App'
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Test the Web App - Unit Tests'
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Publish the Web App - ZIP'
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts for Web App'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'webapp-artifact'


# BUILD THE INTEGRATION ENVIRONMENT IN AZURE
- stage: build_integration
  displayName: 'Build the INT infrastructure in Azure'
  dependsOn: build_app
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'Building the infrastructure for INT environment.'
      vmImage: 'Ubuntu-16.04'
      resourceGroupName: 'integration'
      subscription: $(subscription)

# BUILD THE STAGING ENVIRONMENT IN AZURE
- stage: build_staging
  displayName: 'Build the STAGING infra in Azure'
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'Building the infrastructure for STAGING environment.'
      vmImage: 'Ubuntu-16.04'
      resourceGroupName: 'staging'
      subscription: $(subscription)

# BUILD THE DEMO ENVIORNMENT IN AZURE
- stage: build_demo
  displayName: 'Build the DEMO infras in Azure'
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'Building the infrastructure for DEMO environment'
      vmImage: 'Ubuntu-16.04'
      resourceGroupName: 'demo'
      subscription: $(subscription)

...
