# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
      - job: build
        displayName: build pipeline-dotnet-core
        continueOnError: false
        steps:
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj'
            includesymbols: true
            versioningScheme: 'off'

        # - task: DotNetCoreCLI@2
        #   inputs:
        #     command: 'publish'
        #     publishWebProjects: true


        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'