name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pipelines-dotnet-core
          path: |
            Views
