name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2

     - run: mkdir -p path/to/artifact

     - run: echo hello > path/to/artifact/world.txt

     - uses: actions/upload-artifact@v2
       with:
        name: "artifact-4.0"
        path: path/to/artifact/world.txt
        
     
     - name: Upload client binaries to release
       if: contains(github.ref, 'master')
       uses: svenstaro/upload-release-action@v1-release
       with:
        file: artifact-4.0
        asset_name: artifact-4.0
        tag: "${{ steps.gitversion.outputs.fullSemVer }}"
        overwrite: true
        
      
    
